# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [ ]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor(42)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(42)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [ ]:
# TODO: Create a vector tensor
vector = torch.tensor ([1, 2, 3, 4])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([1, 2, 3, 4])
Number of dimensions: 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [ ]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [ ]:
# TODO: Create a 3D tensor
tensor_3d = torch.arange(1, 9).reshape(2, 2, 2)

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [ ]:
# TODO: Create random tensor
random_tensor = torch.rand(4, 4)

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.6315, 0.1761, 0.7515, 0.6039],
        [0.2143, 0.5752, 0.0740, 0.1705],
        [0.2970, 0.4957, 0.9345, 0.9702],
        [0.3996, 0.4648, 0.9717, 0.4959]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [ ]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(3, 224, 224)

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [ ]:
# TODO: Create zeros tensor
zeros = torch.zeros((5, 5))

# Print details
print(zeros)
print(f"Shape: {zeros.shape}")
print(f"Datatype: {zeros.dtype}")

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Shape: torch.Size([5, 5])
Datatype: torch.float32


### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [ ]:
random_tensor = torch.rand(3, 3)
# TODO: Create ones like
ones_like = torch.ones_like(random)

## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [ ]:
# TODO: Create range tensor
range_tensor =

## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [ ]:

# TODO: Create ones tensor with the same shape
ones_like = torch.ones_like(random_tensor)

# Print details
print("Random tensor:")
print(random_tensor)
print("\nOnes like tensor:")
print(ones_like)

Random tensor:
tensor([[0.6315, 0.1761, 0.7515, 0.6039],
        [0.2143, 0.5752, 0.0740, 0.1705],
        [0.2970, 0.4957, 0.9345, 0.9702],
        [0.3996, 0.4648, 0.9717, 0.4959]])

Ones like tensor:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [15]:
# TODO: Change dtype
float32_tensor = float16_tensor.float()



NameError: name 'float16_tensor' is not defined

## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [ ]:
import torch

# Create random tensor
tensor = torch.rand(2, 3, 4)

# Print properties
print("Shape:", tensor.shape)
print("Dtype:", tensor.dtype)
print("Device:", tensor.device)


Shape: torch.Size([2, 3, 4])
Dtype: torch.float32
Device: cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [ ]:
import torch

# Create tensor
tensor = torch.tensor([10, 20, 30])

# Perform operations
add_5 = tensor + 5
sub_10 = tensor - 10
mul_2 = tensor * 2
div_10 = tensor / 10

# Print results
print("Original:", tensor)
print("Add 5:", add_5)
print("Subtract 10:", sub_10)
print("Multiply by 2:", mul_2)
print("Divide by 10:", div_10)


Original: tensor([10, 20, 30])
Add 5: tensor([15, 25, 35])
Subtract 10: tensor([ 0, 10, 20])
Multiply by 2: tensor([20, 40, 60])
Divide by 10: tensor([1., 2., 3.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [ ]:
import torch

# Create random tensors
A = torch.rand(2, 3)
B = torch.rand(3, 2)

# Matrix multiplication
C = torch.matmul(A, B)

# Print results
print("Tensor A:\n", A)
print("Tensor B:\n", B)
print("Result (A @ B):\n", C)
print("Result shape:", C.shape)


Tensor A:
 tensor([[0.1622, 0.0635, 0.2511],
        [0.4219, 0.0091, 0.5656]])
Tensor B:
 tensor([[0.3847, 0.6188],
        [0.2251, 0.2785],
        [0.8398, 0.4624]])
Result (A @ B):
 tensor([[0.2875, 0.2342],
        [0.6393, 0.5251]])
Result shape: torch.Size([2, 2])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [ ]:
import torch

# Create tensor with values from 0 to 100 (inclusive)
tensor = torch.arange(0, 101)

# Compute statistics
min_val = torch.min(tensor)
max_val = torch.max(tensor)


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [ ]:
import torch

tensor = torch.arange(0, 101)

min_index = torch.argmin(tensor)
max_index = torch.argmax(tensor)

print("Min value:", tensor[min_index].item(), "at index:", min_index.item())
print("Max value:", tensor[max_index].item(), "at index:", max_index.item())



Min value: 0 at index: 0
Max value: 100 at index: 100


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [ ]:
import torch

# Create a tensor of shape (10,)
tensor = torch.arange(10)

print("Original tensor shape:", tensor.shape)
print(tensor)

# Reshape to (2, 5)
reshaped_tensor = tensor.reshape(2, 5)

print("Reshaped tensor shape:", reshaped_tensor.shape)


Original tensor shape: torch.Size([10])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Reshaped tensor shape: torch.Size([2, 5])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [ ]:
import torch

# Create two tensors of shape (2, 2)
tensor1 = torch.tensor([[1, 2],
                        [3, 4]])
tensor2 = torch.tensor([[5, 6],
                        [7, 8]])

# Vertical stacking (along rows)
vertical_stack = torch.vstack((tensor1, tensor2))

# Horizontal stacking (along columns)
horizontal_stack = torch.hstack((tensor1, tensor2))

print("Tensor 1:\n", tensor1)
print("Tensor 2:\n", tensor2)
print("\nVertical Stack:\n", vertical_stack)
print("\nHorizontal Stack:\n", horizontal_stack)


Tensor 1:
 tensor([[1, 2],
        [3, 4]])
Tensor 2:
 tensor([[5, 6],
        [7, 8]])

Vertical Stack:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

Horizontal Stack:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [ ]:
import torch

# Create a tensor of shape (1, 3, 1)
tensor = torch.tensor([[[1], [2], [3]]])

print("Original tensor shape:", tensor.shape)
print(tensor)

# Squeeze the tensor (removes dimensions of size 1)
squeezed_tensor = tensor.squeeze()
print("\nSqueezed tensor shape:", squeezed_tensor.shape)
print(squeezed_tensor)

# Unsqueeze back on dim=0 (adds a dimension at position 0)
unsqueezed_tensor = squeezed_tensor.unsqueeze(0)
print("\nUnsqueezed tensor shape:", unsqueezed_tensor.shape)
print(unsqueezed_tensor)


Original tensor shape: torch.Size([1, 3, 1])
tensor([[[1],
         [2],
         [3]]])

Squeezed tensor shape: torch.Size([3])
tensor([1, 2, 3])

Unsqueezed tensor shape: torch.Size([1, 3])
tensor([[1, 2, 3]])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [ ]:
import torch

# Create an image tensor of shape (3, 100, 100)
# Usually, (channels, height, width)
image_tensor = torch.randn(3, 100, 100)

print("Original shape:", image_tensor.shape)

# Permute to (100, 10


Original shape: torch.Size([3, 100, 100])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [ ]:
import torch

# Create the tensor of shape (1, 3, 3)
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

print("Original tensor:\n", tensor)

# Index to get the value 5
# It's in the first batch (0), second row (1), second column (1)
value_5 = tensor[0, 1, 1]
print("\nValue 5:", value_5.item())

# Index to get the entire second row
# First batch (0), second row (1), all columns (:)
second_row = tensor[0, 1, :]
print("Second row:", second_row)


Original tensor:
 tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

Value 5: 5
Second row: tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [ ]:
import numpy as np
import torch

# Create a NumPy array
np_array = np.array([1, 2, 3, 4])
print("NumPy array:", np_array)

# Convert NumPy array to PyTorch tensor
torch_tensor = torch.from_numpy(np_array)
print("PyTorch tensor:", torch_tensor)


NumPy array: [1 2 3 4]
PyTorch tensor: tensor([1, 2, 3, 4])


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [ ]:
import torch

# Create a PyTorch tensor
tensor = torch.tensor([5, 6, 7, 8])
print("PyTorch tensor:", tensor)

# Convert to NumPy array
np_array = tensor.numpy()
print("NumPy array:", np_array)


PyTorch tensor: tensor([5, 6, 7, 8])
NumPy array: [5 6 7 8]


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [ ]:
import torch

# Set manual seed
torch.manual_seed(77)

# Create the first random tensor
tensor1 = torch.rand(2, 2)
print("Tensor 1:\n", tensor1)

# Set the seed again to ensure reproducibility
torch.manual_seed(77)

# Create the second random tensor
tensor2 = torch.rand(2, 2)
print("\nTensor 2:\n", tensor2)

# Check if the tensors are equal
are_equal = torch.equal(tensor1, tensor2)
print("\nAre the tensors equal?", are_equal)


Tensor 1:
 tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])

Tensor 2:
 tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])

Are the tensors equal? True


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [ ]:
# TODO: Set device
device =

### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [ ]:
import torch

# Create a tensor
tensor = torch.tensor([1, 2, 3, 4])
print("Original tensor:", tensor)

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Move tensor to GPU (if available)
tensor_gpu = tensor.to(device)
print("Tensor on GPU:", tensor_gpu)

# Move tensor back to CPU
tensor_cpu = tensor_gpu.to("cpu")
print("Tensor back on CPU:", tensor_cpu)

# Convert to NumPy array
np_array = tensor_cpu.numpy()
print("NumPy array:", np_array)


Original tensor: tensor([1, 2, 3, 4])
Using device: cpu
Tensor on GPU: tensor([1, 2, 3, 4])
Tensor back on CPU: tensor([1, 2, 3, 4])
NumPy array: [1 2 3 4]
